### ISSUE TITLE
Wish List

### ISSUE THREAD

**Issue by badcat** [andyhqtran/Divi-Resources#1]
How can we ask for Wish List / Suggestion items? 

I'd love to see a way to alter the viewport meta tag to allow EDITING of User Scaling properties.

`<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />`

thanks.

**Comment by andyhqtran** [comment]
@badcat Yeah, that's not a problem!

---

From what I can tell, this is set by WordPress itself... However, with the code module, you can set a work around for it.

``` js
<script>
  document.querySelector('meta[name="viewport"]').setAttribute("content", "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0");
</script>
```

**Comment by badcat** [comment]
So easy!  I thought it was set via the theme and I was trying not to hack the core Divi theme but also didn't want/need to create a child theme just for this one change.  - thanks Andy, -- Kel

**Comment by andyhqtran** [comment]
@badcat no problem! I know what you mean, which is why the module is so powerful! It basically serves as a "child theme" in a way since you can replace almost anything and create almost anything! The awesome part as well, is the fact that you can set it as a global module and lock it!

**Comment by badcat** [comment]
Doh! waitaminute... I think I'm realizing you're expecting this in the "Code Module"-- on a per page/post etc basis in the Builder?  I was thinking it would be added in the Theme Options > Integration tab  (Enable Header Code then..  add Code to Head)

**Comment by andyhqtran** [comment]
@badcat Oh yeah, I forgot about that. That would work as well!

**Comment by badcat** [comment]
For anyone following along - I just added as a meta tag in the head as I stated above.  Not the JS.
Since it comes after the default Divi metatag, the browser uses the last one it finds (Well I hope that's how it renders out :)
e.g. 
`<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes" />`

Thanks Andy for making me think  👍

**Comment by andyhqtran** [comment]
@badcat That's great to hear! Just like how script tags are handled and CSS selectors, the last one overrides the first! :)
