### ISSUE TITLE
H!, I'm facing a problem to run background video on safari

### ISSUE THREAD

**Issue by shahjehanali1** [andyhqtran/Divi-Resources#16]
H!, I'm facing a problem to run background video on safari
Can you help me to figure this out
https://upwardprojects.laneterralever.com/contact-us/

**Comment by tdavidrussell** [comment]
It's a know Safari browser limitation it blocks the background videos to be played automatically by default. elegantthemes.com are working on this to find a solution that will override the default Safari settings. 

See there form entry https://www.elegantthemes.com/forum/viewtopic.php?f=22&t=813557&hilit=safari+video&p=4480863#p4480863
