### ISSUE TITLE
Landing Page Kit takes forever

### ISSUE THREAD

**Issue by taddmencer** [andyhqtran/Divi-Resources#5]
Every time I try and import the landing page kit it stalls out at 67%. I've tried it on three different WordPress installations and it does it on each one. Is this happening for anyone else, or just me?

**Comment by pixelxcode** [comment]
I had that issue and someone said it was due to EWWW image optimiser.

Do you have this plugin installed? I disabled it and then I could upload the layouts.

**Comment by taddmencer** [comment]
That was it, fantastic! Thanks for the heads up!

**Comment by andyhqtran** [comment]
Looks like this is fixed! Thanks @pixelxcode
