### ISSUE TITLE
Discrepancy on Homepage For Enterprise Businesses

### ISSUE THREAD

**Issue by dm-chechik** [andyhqtran/Divi-Resources#7]
In the Free Divi Layout Pack For Modern Homepages & Single Page Websites announced the A Homepage For Enterprise Businesses with two buttins on the screenshot. But after importing this pack customer see only one button.

**Comment by andyhqtran** [comment]
@dm-chechik could you provide a screen of the issue? As well as your Divi + WordPress version.

**Comment by dm-chechik** [comment]
@andyhqtran Here is the page on our anouncment
![image](https://cloud.githubusercontent.com/assets/20072036/17810141/031adb9e-6624-11e6-8084-3deb07bcce4b.png)
And here the page added from library
![image](https://cloud.githubusercontent.com/assets/20072036/17810195/5ba73dac-6624-11e6-9b28-007ef89ab1c1.png)
As you can see layout has the Fullwidth Slider on top of the page. As I know the Fullwidth Slider allow only one button within it.

**Comment by andyhqtran** [comment]
The image provided in the announcement is an exported PNG from Sketch. The JSON file that was provided used the features provided by Divi. It's possible to achieve 2 buttons if you play around with the layout some more.
